# Makefile for CS 433

# Maintain the following definitions:
#
#       HW      current project (e.g., hw2)
#	HDR	all header files (*.h)
#	SRC	all C source files (*.c)
#	HDRg	all header files (*.h) generated by programs
#	SRCg	all C source files (*.c) generated by programs
#	OBJ	all object files (*.o)

# Use the following make targets:
#
#	all	(or nothing) to build your program (into "yococo")
#	depend	to print header file dependencies

HW = hw9

# ***** add any #YOCO files you want to submit to the following line: ****
YOCO =

HDR = symtab.h syntax.h syntree.h codegen.h
SRCc = main.c symtab.c syntree.c printtree.c printdecl.c resolve.c \
       codegen-lowlev.c codegen-expr.c codegen-stmts.c
SRC = $(SRCc) parser.y scanner.l
OBJ = main.o symtab.o syntree.o printtree.o printdecl.o resolve.o \
      parser.o scanner.o codegen-lowlev.o codegen-expr.o codegen-stmts.o

# program generated files:
HDRg = y.tab.h
SRCg = scanner.c parser.c

BDIR = /home/schar/cs433
#DIR =  $(BDIR)/$(HW)

GRD = $(SRC) $(HDR) Makefile $(YOCO)

DBG = -g
OPT = # -O
WARN = -W -Wall
CFLAGS = $(DBG) $(OPT) $(WARN) #-I$(DIR)
#LFLAGS = -i  # instruct lex to operate case-insensitive
CC = gcc
LINK = gcc
YACC = yacc -dv

yococo: $(OBJ)
	$(LINK) -o yococo $(OBJ)

# explicit rules for parser and scanner to avoid warning messages
parser.o: parser.c
	$(CC) $(DBG) $(OPT) -c $< -o $@
scanner.o: scanner.c
	$(CC) $(DBG) $(OPT) -c $< -o $@

clean:
	rm -f $(HDRg) $(SRCg) $(OBJ) *.bak y.output core*

submit:
	$(BDIR)/bin/sub433 $(GRD)

check:
	$(BDIR)/bin/chk433 test$(HW).yoco

depend:
	gcc -MM $(CFLAGS) $(SRCc)

# include dependencies here manually:
main.o: main.c symtab.h syntree.h
symtab.o: symtab.c symtab.h
syntree.o: syntree.c symtab.h syntree.h
printtree.o: printtree.c symtab.h syntree.h
printdecl.o: printdecl.c symtab.h syntree.h
resolve.o: resolve.c symtab.h syntree.h
codegen-lowlev.o: codegen-lowlev.c symtab.h syntree.h codegen.h
codegen-expr.o: codegen-expr.c symtab.h syntree.h codegen.h
codegen-stmts.o: codegen-stmts.c symtab.h syntree.h codegen.h
